name: Backend Dependency Audit

on:
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 6 * * 1' # Weekly on Monday 06:00 UTC

permissions:
  contents: read

jobs:
  audit:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: packages/backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install pip-audit
        run: |
          python -m pip install --upgrade pip
          pip install pip-audit
      - name: Run pip-audit
        run: |
          pip-audit -r requirements.txt || true
