name: Frontend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

concurrency:
  group: frontend-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-typecheck:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci

      - name: Lint
        run: |
          npm run lint --if-present

      - name: Typecheck and Build
        env:
          NODE_ENV: production
          BACKEND_URL: http://localhost:3001
        run: |
          npx tsc -v >/dev/null 2>&1 || true
          npx tsc --noEmit || true
          npm run build
